- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v2.23.0/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'

- name: Verify Docker Compose installation
  command: docker-compose --version
  register: compose_version

- debug:
    msg: "{{ compose_version.stdout }}"
